# Normal prefix.
set-option -g prefix C-a
# Send prefix through tmux, for example to the underlying screen.
bind-key a send-prefix

# Bigger scrollback buffer.
set -g history-limit 4096

# Make tmux *not* launch login shell.
set -g default-command "${SHELL}"

# Keep tmux mouse support disabled by default and let the terminal handle selection and paste.
set -g mouse off

# Toggle status bar.
bind-key b set-option status

# Toggle tmux mouse support.
bind-key m set-option mouse

# Close current window.
bind k confirm kill-window

# Reload key.
bind-key r source-file ~/.tmux.conf

# Search buffer by `/`.
bind-key / copy-mode \; send-key ?

# Set current working directory of new panes/windows to the current directory of active pane.
bind-key R attach -c "#{pane_current_path}"

# Split window into panes, horizontal or vertical.
bind-key h split-window -h
bind-key v split-window -v

# Move or join windows into panes.
bind-key J command-prompt -p "join pane from:"  "join-pane -s '%%'"
bind-key S command-prompt -p "send pane to:"  "join-pane -t '%%'"

# Quick access to sessions.
bind-key s choose-session

# TERM variable and title.
#set -g default-terminal "screen-256color" 
set -g set-titles on
set -g set-titles-string '#T (tmux@#H)'

# Disable repeatable select pane keys.
bind-key Up select-pane -U
bind-key Down select-pane -D
bind-key Left select-pane -L
bind-key Right select-pane -R

# Start counting windows from 1.
set -g base-index 1

# Colors and format of status bar, menus, etc.
set -g status-left ' '
set -g status-style 'bg=colour235 fg=colour252'
set -g message-style 'bg=colour236 fg=colour252'

# '<prefix>, T' to show window title in status bar. '<prefix>, t' to display clock there.
bind-key T set -g status-right '#[bg=black]#[fg=colour245] #T '
bind-key t set -g status-right '#[bg=black]#[fg=colour245] %d-%m-%Y %H:%M '

set -g status-right '#[bg=black]#[fg=colour245] %d-%m-%Y %H:%M '
set -g status-right-length 50
set-window-option -g window-status-format ' #[fg=colour245]#I:#[fg=colour250]#W '
set-window-option -g window-status-current-format '#[bg=colour0]#[fg=colour245] #I#[fg=colour245]:#[fg=colour252]#W '

# Renumber windows after closing one of them.
set-option -g renumber-windows on

# Dump entire pane to file of choosing.
bind-key P command-prompt -p 'Write scrollback to a file:' -I '~/tmp/tmux-scrollback-dump' 'capture-pane -S -131072; save-buffer %1; delete-buffer'


bind-key l display-menu \
    -T "Select pane Layout" \
    "Even Horizontal" 1 "select-layout even-horizontal" \
    "Even Vertical" 2 "select-layout even-vertical" \
    "Main Horizontal" 3 "select-layout main-horizontal" \
    "Main Vertical" 4 "select-layout main-vertical" \
    "Tiled" 5 "select-layout tiled"
