#!/usr/bin/env ansible-playbook

- name: aion
  gather_facts: true
  gather_subset:
    - min
  hosts: [all]
  vars:
    confmgmt:
      homebrew:
        user: piotr
        formulas:
          - ffmpeg-full
          - svt-av1
          - codex
      dnf:
        packages:
          - netcat
          - socat
          - iotop
          - acl
          - bubblewrap
          - ncdu
          - ripgrep
          - sqlite
          - jq
          - aria2
          - avahi
          - wireguard-tools
          - net-tools
          - tmux
          - distrobox
          - borgbackup
          - mkvtoolnix
          - rclone
          - zsh
          - syncthing
          - tailscale
          - lm_sensors
          - rsync
          - htop
          - btop
          - make
          - cmake
          - zsh
          - podman
          - vim
          - wget
          - aria2
          - gcc
          - gcc-c++
          - make
          - cmake
          - glibc-devel
          - glibc-static
          - pkgconf-pkg-config
          - kernel-headers
          - golang
          - rust
          - nodejs24
          - nodejs24-npm
      sshd: 
      pam:
      sudo:
      udev:
      sysctl:
      systemd:
        logind:
          linger_users:
            - piotr
      home_files:
        files:
          root:
            - bash
            - zsh
            - tmux
            - git
            - vim
          piotr:
            - bash
            - zsh
            - mpv
            - tmux
            - git
            - vim
  roles:
    - role: meta
