#!/usr/bin/env ansible-playbook

- name: deucalion
  gather_facts: true
  gather_subset:
    - min
  hosts: [all]
  vars:
    confmgmt:
      homebrew:
        user: deck
        formulas:
          - ffmpeg-full
          - borgbackup
          - mkvtoolnix
          - rust
          - rclone
          - yt-dlp
          - mpv
          - asdf
          - make
          - gcc
          - golang
      sshd:
      systemd:
        logind:
          linger_users:
            - deck
          kill_user_processes: False
      home_files:
        files:
          root:
            - bash
            - zsh
            - tmux
            - git
            - vim
          deck:
            - bash
            - zsh
            - mpv
            - wezterm
            - tmux
            - git
            - vim
      steamos:
        preserve:
          - /etc/ssh/sshd_config.d/99-auth.conf
          - /etc/systemd/logind.conf.d/xyz-preserve-user-processes.conf
        update: True
  roles:
    - role: meta
