#!/usr/bin/env ansible-playbook

- name: hagane
  gather_facts: true
  gather_subset:
    - min
  hosts: [all]
  vars:
    confmgmt:
      homebrew:
        user: piotr
        formulas:
          - ffmpeg-full
          - svt-av1
          - borgbackup
          - mkvtoolnix
          - rust
          - rclone
          - yt-dlp
          - codex
      apt:
        packages:
          - fzy
          - acl
          - aria2
          - avahi-daemon
          - wireguard
          - net-tools
          - firejail
          - tmux
      sshd: 
      pam:
      udev:
      sysctl:
      home_files:
        files:
          root:
            - bash
            - zsh
            - tmux
            - git
          piotr:
            - bash
            - zsh
            - mpv
            - tmux
            - git
  roles:
    - role: meta
