#!/usr/bin/env ansible-playbook

- name: steamdeck
  gather_facts: true
  gather_subset:
    - min
  hosts: [all]
  vars:
    confmgmt:
      homebrew:
        user: deck
        formulas:
          - fzy
          - rclone
          - yt-dlp
          - mpv
          - tmux
          - asdf
      sshd:
      home_files:
        files:
          root:
            - bash
            - zsh
            - tmux
          deck:
            - bash
            - zsh
            - mpv
            - tmux
  roles:
    - role: meta
