#!/usr/bin/env ansible-playbook

- name: tomoyo
  gather_facts: true
  gather_subset:
    - min
  hosts: [all]
  vars:
    confmgmt:
      rpm_ostree:
        packages:
          - zsh
          - syncthing
          - htop
          - jetbrains-mono-fonts-all
          - vim
          - tailscale
          - lm_sensors
          - docker-cli
          - virt-manager
          - btop
          - tmux
          - steam
          - steam-devices
          - gamescope
          - gcc
          - gcc-c++
          - make
          - cmake
          - glibc-devel
          - glibc-static
          - pkgconf-pkg-config
          - kernel-headers
          - golang
          - rust
        kargs:
          - amdgpu.abmlevel=0
      flatpak:
        packages:
          - io.github.ilya_zlobintsev.LACT
          - it.mijorus.gearlever
      homebrew:
        user: piotr
        formulas:
          - ffmpeg-full
          - svt-av1
          - borgbackup
          - mkvtoolnix
          - rclone
          - yt-dlp
          - mpv
          - ripgrep
          - codex
      sshd: 
      plasmalogin:
      home_files:
        files:
          root:
            - bash
            - zsh
            - tmux
            - git
            - vim
          piotr:
            - bash
            - zsh
            - mpv
            - wezterm
            - tmux
            - git
            - vim
  roles:
    - role: meta
