#!/usr/bin/env ansible-playbook

- name: tomoyo
  gather_facts: true
  gather_subset:
    - min
  hosts: [all]
  vars:
    confmgmt:
      rpm_ostree:
        packages:
          - zsh
          - syncthing
          - htop
          - jetbrains-mono-fonts-all
          - vim
          - tailscale
          - lm_sensors
          - docker-cli
          - virt-manager
          - btop
          - firejail
          - tmux
          - steam
          - steam-devices
        kargs:
          - amdgpu.abmlevel=0
        system_groups:
          - docker
          - libvirt
      flatpak:
        packages:
          - io.github.ilya_zlobintsev.LACT
          - it.mijorus.gearlever
      homebrew:
        user: piotr
        formulas:
          - ffmpeg
          - svt-av1
          - borgbackup
          - mkvtoolnix
          - rust
          - rclone
          - yt-dlp
          - mpv
          - ripgrep
          - fzy
      sshd: 
      sddm:
      home_files:
        files:
          root:
            - bash
            - zsh
            - tmux
            - git
          piotr:
            - bash
            - zsh
            - mpv
            - wezterm
            - tmux
            - git
  roles:
    - role: meta
