#!/usr/bin/env ansible-playbook

- name: virtue
  gather_facts: true
  gather_subset:
    - min
  hosts: [all]
  vars:
    confmgmt:
      rpm_ostree:
        packages:
          - zsh
          - syncthing
          - htop
          - jetbrains-mono-fonts-all
          - tmux
        kargs:
          - amdgpu.abmlevel=0
      flatpak:
        packages:
          - io.github.ilya_zlobintsev.LACT
          - it.mijorus.gearlever
      homebrew:
        user: bazzite
        formulas:
          - fzy
          - ffmpeg-full
          - svt-av1
          - borgbackup
          - mkvtoolnix
          - rust
          - rclone
          - yt-dlp
          - mpv
          - asdf
      sshd:
      sddm:
      home_files:
        files:
          root:
            - bash
            - zsh
            - tmux
            - git
          bazzite:
            - bash
            - zsh
            - mpv
            - wezterm
            - tmux
            - git
  roles:
    - role: meta
