PGUP       seek   300      
PGDWN      seek   -300     
ENTER      quit
KP_ENTER   quit
ESC        quit
\          quit

, playlist-prev
. playlist-next

S   screenshot

# Drop volume from mouse wheel / touchpad side slide
WHEEL_LEFT  ignore
WHEEL_RIGHT ignore

# Drop volume hotkeys, they are handled by acpid events and are system wide.
VOLUME_UP   ignore
VOLUME_DOWN ignore

z add   gamma   -1
x add   gamma   +1

Z add sub-delay -0.1
X add sub-delay +0.1

s cycle-values sub-ass-override "force" "strip" "no"
r cycle_values video-rotate 90 180 270 0
c cycle-values glsl-shaders "~/.config/mpv/adaptive-sharpen-luma.glsl" ""

b add sub-pos -1
n add sub-pos +1
