- name: sysctl
  tags: [sysctl]
  when: ansible_facts.system == "Linux"
  block:
    - name: gather hardware facts
      when: ansible_facts.memtotal_mb is not defined
      setup:
        gather_subset:
          - "!all"
          - hardware

    - name: virtual memory subsystem tuning config
      notify: apply system control settings
      copy:
        dest: "{{ sysctl_vm_file }}"
        owner: root
        group: root
        mode: 0644
        content: |
          # Managed by conf-mgmt.
          {% for setting in sysctl_vm_settings %}
          {{ setting.name }} = {{ setting.value }}
          {% endfor %}

    - name: AppArmor system control settings config
      notify: apply system control settings
      copy:
        dest: "{{ sysctl_apparmor_file }}"
        owner: root
        group: root
        mode: 0644
        content: |
          # Managed by conf-mgmt.
          {% for setting in (sysctl_apparmor_settings | combine(confmgmt.sysctl | default({}, true))) | dict2items %}
          {{ setting.key }} = {{ setting.value }}
          {% endfor %}
