- name: rpm-ostree
  tags: [rpm_ostree]
  block:
  - name: manage rpm-ostree deployment
    confmgmt_rpm_ostree:
      packages: "{{ confmgmt.rpm_ostree.packages | default([]) }}"
      kargs: "{{ confmgmt.rpm_ostree.kargs | default([]) }}"
      upgrade: True
