- name: home_files
  tags: [home_files]
  block:
    - name: Look up user account details
      confmgmt_user_info:
        names: "{{ confmgmt.home_files.files | default({}) | list }}"
      register: home_files_users

    - name: Include dotfile tasks
      loop: "{{ (confmgmt.home_files.files | default({})) | dict2items | subelements('value') }}"
      loop_control:
        loop_var: pair
        label: "{{ pair.0.key }} -> {{ pair.1 }}"
      vars:
        user: '{{ pair.0.key }}'
        home: '{{ home_files_users["users"][user]["home"] }}'
        uid: '{{ home_files_users["users"][user]["uid"] }}'
        gid: '{{ home_files_users["users"][user]["gid"] }}'
        dotfile:  "{{ pair.1 }}"
        overrides: "{{ (confmgmt.home_files.overrides | default({})).get(dotfile, None) }}"
      include_tasks:
        file: "{{ dotfile }}.yml"
